SYNONYMS = {

"humidity": "atmospheric_moisture",
"moisture": "atmospheric_moisture",
"dampness": "atmospheric_moisture",
"wet air": "atmospheric_moisture",
"water vapour": "atmospheric_moisture",
"water vapor": "atmospheric_moisture",
"soil water": "soil_moisture",
"ground moisture": "soil_moisture",
"heat": "temperature",
"cold": "temperature",
"warmth": "temperature",
"rain": "precipitation",
"rainfall": "precipitation",
"cloud": "cloud",
"cloudiness": "cloud",
"cloud cover": "cloud",
"overcast": "cloud",
"air pressure": "pressure",
"barometric pressure": "pressure",
"atmospheric pressure": "pressure",
"air movement": "wind",
"airflow": "wind",
"tidal state": "tide",
"tidal height": "tide",
"high tide": "tide",
"low tide": "tide",
"ocean conditions": "marine_conditions",
"sea conditions": "marine_conditions",
"waves": "marine_conditions",
"ocean currents": "marine_conditions",
"ground temperature": "soil_temperature",
"soil heat": "soil_temperature",
"plants": "vegetation",
"greenness": "vegetation",
"plant activity": "vegetation",
"NDVI": "vegetation",
"geological province": "geology",
"tectonic zone": "geology",
"rock": "geology",
"earthquake": "earthquake",
"earthquakes": "earthquake",
"seismic activity": "earthquake",
"earth tremor": "earthquake",
"altitude": "elevation",
"height above sea level": "elevation",
"sunspots": "solar_activity",
"sunspot number": "solar_activity",
"solar cycle": "solar_activity",
"solar position": "sun",
"solar body": "sun",
"lunar state": "moon",
"lunar position": "moon",
"planets": "planetary_positions",
"planetary configuration": "planetary_positions",
"planetary alignment": "planetary_positions",
"nighttime": "night",
"darkness": "night",
"nocturnal": "night",
"seasonal state": "season",
"winter": "season",
"summer": "season",
"spring": "season",
"autumn": "season",
"fall": "season"
}